# Generated by Django 5.2.15 on 2026-06-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_trueskillplayerrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingUpdateJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('aga', 'AGA ratings (raago C++)'), ('ttt', 'TrueSkill Through Time')], max_length=10)),
                ('status', models.CharField(choices=[('running', 'Corriendo'), ('success', 'Terminado OK'), ('error', 'Error')], default='running', max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
