# Generated by Django 5.2.15 on 2026-06-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_player_is_aago_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='reason',
            field=models.CharField(choices=[('points', 'Points'), ('resignation', 'Resignation'), ('walkover', 'Walkover'), ('timeout', 'Timeout'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=16),
        ),
    ]
